profiles:
  - name: 'ghe_destination'
    url: 'https://ghe.example.com/api/v3'
    scm_type: 'github'
    organization: 'some_organization_at_destination'
    repository: 'your_ghe_repository'
    token: 'ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

  - name: 'gitlab_source'
    url: 'http://gitlab.example.com'
    scm_type: 'gitlab'
    organization: 'some_organization_at_source'
    repository: 'general'
    token: 'GITLABTOKENGITLABTOK'
