# install docker-ce from the upstream docker repository
---
- name: install
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tasks:
    - name: setup docker-ce stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
        state: present

    - name: install docker-ce
      apt:
        name: "{{ docker_packages }}"
        update_cache: yes
        with_items: docker_packages
      vars:

    - name: add ansible_ssh_user to docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
