# install ceph from upstream ceph repository
# change ceph_stable_release: as you like
---
- name: install
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars:
    ceph_stable_release: "nautilus"
  tasks:
    - name: import ceph release key
      apt_key:
        url: https://download.ceph.com/keys/release.asc
        state: present

    - name: setup ceph repository
      apt_repository:
        repo: deb https://download.ceph.com/debian-{{ ceph_stable_release }}/ {{ ansible_distribution_release }} main
        state: present
        update_cache: yes

    - name: install
      apt:
        name: ceph
        state: present
        autoremove: yes
        update_cache: yes

