---
#- hosts:
#  - node
#  gather_facts: false
#  any_errors_fatal: true
#  become: True

- name: play1
  hosts:
    - node
  gather_facts: false
  any_errors_fatal: true
  become: True
  tasks:
    - name: task11
      debug:
        msg: "task11"

    - name: task12 - by setting is_bailout=true, task14 & later can be skipped.
      #set_fact: is_bailout=true
      set_fact: is_bailout=false

    - name: task13 - abort a PLAY, not a playbook
      meta: end_play
      when: is_bailout is defined and not is_bailout

    - name: task14
      debug:
        msg: "task14: is_bailout={{ is_bailout }}. Not skipped"

    - name: task15
      debug:
        msg: "task15: is_bailout={{ is_bailout }}. Not skipped"

- name: play2 - a normal play
  hosts:
    - node
  gather_facts: false
  any_errors_fatal: true
  become: True
  tasks:
    - name: task21
      debug:
        msg: "task21"

- name: play3 - using import_playbook (a sub playbook) from a play
  import_playbook: scenario/subplay1.yml
  #include_playbook: scenario/subplay1.yml
  when: is_bailout is defined and not is_bailout
  # This 'when' is associated with a 'import_playbook' (task?), not play3.

- name: play4 - using include_tasks from a play
  hosts:
    - node
  gather_facts: false
  tasks:
    - name: play4-task1
      include_tasks: scenario/subtasks1.yml
      when: is_bailout is defined and not is_bailout
      # This 'when' must be associated with a task, not a play.

